In [1]:
import numpy as np
from sklearn.model_selection import KFold

In [2]:
X = np.array([[11,12],[21,22],[31,32],[41,42],[51,52],[61,62]])
X

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62]])

In [3]:
y = np.array([100,200,300,400,500,600])
y

array([100, 200, 300, 400, 500, 600])

In [4]:
kf = KFold(n_splits=3,shuffle=True,random_state=1)

In [5]:
for train_index, test_index in kf.split(y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    #print(X_train)
    print(y_train)

[0 3 4 5]
[100 400 500 600]
[1 2 3 5]
[200 300 400 600]
[0 1 2 4]
[100 200 300 500]


In [6]:
X

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62]])